baseurl = "https://plantbasedgames.io/blog/"
languageCode = "en-us"
theme = "hugo-theme-terminal"
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    title = "Plant Based Games"
    subtitle = ""
    keywords = ""
    copyright = "(C) 2025 Rasmus Neckelmann"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Plant Based Games"
      logoHomeLink = "/blog/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "trolddom"
        name = "Trolddom"
        url = "https://trolddom.com"
	
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"

